/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as SearchRouteImport } from './routes/search'
import { Route as MovieIdRouteImport } from './routes/movie.$id'
import { Route as PersonIdRouteImport } from './routes/person.$id'
import { Route as TvIdRouteImport } from './routes/tv.$id'
import { Route as ApiTmdbSplatRouteImport } from './routes/api/tmdb.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieIdRoute = MovieIdRouteImport.update({
  id: '/movie/$id',
  path: '/movie/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonIdRoute = PersonIdRouteImport.update({
  id: '/person/$id',
  path: '/person/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TvIdRoute = TvIdRouteImport.update({
  id: '/tv/$id',
  path: '/tv/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTmdbSplatRoute = ApiTmdbSplatRouteImport.update({
  id: '/api/tmdb/$',
  path: '/api/tmdb/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/favorites': typeof FavoritesRoute
  '/search': typeof SearchRoute
  '/movie/$id': typeof MovieIdRoute
  '/person/$id': typeof PersonIdRoute
  '/tv/$id': typeof TvIdRoute
  '/api/tmdb/$': typeof ApiTmdbSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/favorites': typeof FavoritesRoute
  '/search': typeof SearchRoute
  '/movie/$id': typeof MovieIdRoute
  '/person/$id': typeof PersonIdRoute
  '/tv/$id': typeof TvIdRoute
  '/api/tmdb/$': typeof ApiTmdbSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/favorites': typeof FavoritesRoute
  '/search': typeof SearchRoute
  '/movie/$id': typeof MovieIdRoute
  '/person/$id': typeof PersonIdRoute
  '/tv/$id': typeof TvIdRoute
  '/api/tmdb/$': typeof ApiTmdbSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalog'
    | '/favorites'
    | '/search'
    | '/movie/$id'
    | '/person/$id'
    | '/tv/$id'
    | '/api/tmdb/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalog'
    | '/favorites'
    | '/search'
    | '/movie/$id'
    | '/person/$id'
    | '/tv/$id'
    | '/api/tmdb/$'
  id:
    | '__root__'
    | '/'
    | '/catalog'
    | '/favorites'
    | '/search'
    | '/movie/$id'
    | '/person/$id'
    | '/tv/$id'
    | '/api/tmdb/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogRoute: typeof CatalogRoute
  FavoritesRoute: typeof FavoritesRoute
  SearchRoute: typeof SearchRoute
  MovieIdRoute: typeof MovieIdRoute
  PersonIdRoute: typeof PersonIdRoute
  TvIdRoute: typeof TvIdRoute
  ApiTmdbSplatRoute: typeof ApiTmdbSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie/$id': {
      id: '/movie/$id'
      path: '/movie/$id'
      fullPath: '/movie/$id'
      preLoaderRoute: typeof MovieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/person/$id': {
      id: '/person/$id'
      path: '/person/$id'
      fullPath: '/person/$id'
      preLoaderRoute: typeof PersonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv/$id': {
      id: '/tv/$id'
      path: '/tv/$id'
      fullPath: '/tv/$id'
      preLoaderRoute: typeof TvIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tmdb/$': {
      id: '/api/tmdb/$'
      path: '/api/tmdb/$'
      fullPath: '/api/tmdb/$'
      preLoaderRoute: typeof ApiTmdbSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogRoute: CatalogRoute,
  FavoritesRoute: FavoritesRoute,
  SearchRoute: SearchRoute,
  MovieIdRoute: MovieIdRoute,
  PersonIdRoute: PersonIdRoute,
  TvIdRoute: TvIdRoute,
  ApiTmdbSplatRoute: ApiTmdbSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
